### ISSUE TITLE
Custom Fields Rest API の改善案

### ISSUE THREAD

**Issue by sanak** [redmine-patch-meetup/redmine-dev-mirror#14]
## 問題点

現状、Custom Fields Rest API (https://www.redmine.org/projects/redmine/wiki/Rest_CustomFields) は、Admin権限でないとアクセスできませんが、Rest APIクライアント開発チームから、
1. アカウント登録時に、ユーザーのカスタムフィールド情報を知りたい
2. レポート登録時に、レポートのカスタムフィールド情報を知りたい

という要望がありました。

## 改善案

改善案としては、以下のNo.1・2のどちらかになると考えています。
1. カスタムフィールドの読み取りについては、ログインなしの匿名ユーザー(anonymous)でも取得可能なようにする
   - 実装自体はシンプルに済むはず？
2. カスタムフィールド情報自体がセキュアであるべきと考えられる場合は、ロール毎に読み取りが可能かの制御と、ログインユーザ毎にアクセス可能なカスタムフィールドを返せるようにする
   - ログインユーザーの所属プロジェクト毎にアクセス可能なカスタムフィールドが動的に変更されるので、実装が少し(or かなり)複雑になる？

## その他

以下も対応できるとなお良いと考えています。
- APIクライアントとして見た場合、それぞれの目的に応じて情報取得できることが望ましいので、クエリー可能(例: ユーザーのカスタムフィールドのみ取得、レポートのカスタムフィールドのみ取得など)として欲しい。

**Comment by ishikawa999** [comment]
仕様面を詰める必要あり

**Comment by ishikawa999** [comment]
https://scrapbox.io/redmine-patch/第4回/Custom_Fields_Rest_API_の改善案_#14

**Comment by ishikawa999** [comment]
メモ:

カテゴリやステータスなどでも入力できる項目が変わるため、どのAPIにカスタムフィールドの情報をつけてあげれば良いのか迷う。

案:
* project_idを渡し、そのプロジェクトに対して自分(Member)の権限で見ることができるカスタムフィールドのリストを取得するAPIを作る(自分で見ることができるカスタムフィールドを簡単に取得できるかが怪しい)
* カスタムフィールドのidをキーとして、そのidでカスタムフィールドの詳細情報をAPIで取得できる みたいなAPIを作る(GET custom_fields/:id)(この機能だけの場合、そのidはHTMLの方をスクレイピングして取得する必要があるが、実装はしやすそう。権限的にOKかは要チェック)

**Comment by sanak** [comment]
プロジェクトに関しては、Redmine 4.2からAPI側で対応しているようでした。
- [Feature #33301: Add option to include enabled issue custom fields in projects#show API response - Redmine](https://www.redmine.org/issues/33301)

ユーザーに関しては、下記で `/account/register.json` がJSONのGET/POSTに正式に対応する形になれば、不要となるかもしれません。
- #15 
- [Defect #25296: RestAPI doesn't allow anonymous account registration but web interface does. - Redmine](https://www.redmine.org/issues/25296#note-2)

**Comment by sanak** [comment]
redmine.tokyoの過去(第15回)勉強会で下記のLTがあったようで、Issues APIに関しても、もう少し必要と思われる点がありましたので、再度取り組み候補に挙げさせて頂きます。
> LT6：umesan さん録画  
> 　タイトル：「Redmine Rest APIの現在の困りごと」  
> 　概要　 ：Redmine Rest APIの現在の困りごとを共有させて頂きます  
>　　　　　 http://www.redmine.org/issues/18875

**Comment by sanak** [comment]
一つ上のIssues APIに関しては、別の #69 で現在対応中なので、こちらはクローズします。
