### ISSUE TITLE
Projects Rest API の改善案

### ISSUE THREAD

**Issue by sanak** [redmine-patch-meetup/redmine-dev-mirror#17]
## 問題点

1. 現状、Projects Rest API (https://www.redmine.org/projects/redmine/wiki/Rest_Projects) では、ルート(`parent_id=nil`)のプロジェクトのみを取得したい場合も、まずはプロジェクト全体を取得する必要がある。

## 改善案

1. GETリクエスト時に、`parent_id=nil` でフィルタできるようにして欲しい。

**Comment by ishikawa999** [comment]
name, idしか情報としてないので、せめてparent_id、できればその他のProjectの情報も増やしてほしい。

**Comment by ishikawa999** [comment]
Redmine4.1からプロジェクトのフィルタやカスタムクエリが利用できるようになり、フィルタ項目の中にSubproject Ofという項目があります。
APIでもparent_idで絞り込みができそうです。
 イメージ: `http://<Redmine url>/projects.json?key=<Redmine API Key>&f[]=parent_id&op[parent_id]=!*`

**Comment by sanak** [comment]
@ishikawa999 上記情報、ありがとうございます！
業務の方で利用しているRedmineがまだ4.0ベースなのですが、11月リリース予定のRedmica1.2への切り替えも含めて、検討するようにします。
