### ISSUE TITLE
カスタムフィールドを持つモデル(Project/User/Version)の Rest API 改善案

### ISSUE THREAD

**Issue by sanak** [redmine-patch-meetup/redmine-dev-mirror#18]
## 問題点

1. 現状、Issues 以外のカスタムフィールドを持つモデル(Project/User/Version)の Rest API は、カスタムフィールドでのフィルタをサポートしていないため、Rest APIクライアント側では、一度全体を取得した後、フィルタを行う必要がある。

## 改善案

1. GETリクエスト時に、パラメータでカスタムフィールドでのフィルタが可能なようにして欲しい。
   - 例: `/versions?cf_1=xxx` など (※ #14 にも関連)

**Comment by ishikawa999** [comment]
Issueではcf_nでできているようなので、そちらを参考にすると良さそう

**Comment by fkdkent** [comment]
Projectでもいけてそう。User, Versionはまだ未実装？

**Comment by fkdkent** [comment]
https://scrapbox.io/redmine-patch/%E7%AC%AC4%E5%9B%9E%2F%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89%E3%82%92%E6%8C%81%E3%81%A4%E3%83%A2%E3%83%87%E3%83%AB(Project%2FUser%2FVersion)%E3%81%AE_Rest_API_%E6%94%B9%E5%96%84%E6%A1%88_%2318

**Comment by sanak** [comment]
こちら、上記ScrapBoxの最後に記載頂いた、 `プラグインで controller にパッチングするのも一つの手` の方法で大丈夫そうでした。

User/Versionへのフィルタ機能の追加は大きな変更になりそうなので、本家の方にIssueがなければ作成し、こちらはその後、クローズするようにします。

**Comment by sanak** [comment]
こちら、一旦クローズします。
