### ISSUE TITLE
CIのPostgreSQLのバージョンをあげる

### ISSUE THREAD

**Issue by ishikawa999** [redmine-patch-meetup/redmine-dev-mirror#23]
今は9.xくらい

**Comment by sanak** [comment]
こちらですが、別件で調査した際、PostgreSQLの9.x系は昨年にサポートを終えた(EOL)ようでしたので、念のため記載します。
(現在は、10がサポートされている最も古いバージョンのようです。(~2022/11/10まで))
https://www.postgresql.org/support/versioning/
