### ISSUE TITLE
プロジェクトの概要画面で公開範囲がわかるようにする

### ISSUE THREAD

**Issue by ishikawa999** [redmine-patch-meetup/redmine-dev-mirror#27]
案:
- 公開・非公開のバッジを表示する
- 公開の場合、メンバーブロックの中に「ログイン済みの全ユーザーがアクセスできます。」/「ネットワーク上の誰もがアクセスできます。」という補足を入れる
(l(:text_project_is_public_non_member), l(:text_project_is_public_anonymous)が使えそう。 http://blog.redmine.jp/articles/project-visibility/ に書いてあるように、設定によって公開範囲も変わる)

**Comment by ishikawa999** [comment]
公式にチケット無し

**Comment by ishikawa999** [comment]
https://www.redmine.org/issues/35044 チケットが作られた。
サンプル実装として動くコードも書かれているため、テストを追加したらコミットされそう

**Comment by matobaa** [comment]
https://www.redmine.org/issues/35044#note-6
投稿済みのためクローズします。
