### ISSUE TITLE
プロジェクトを公開する権限を追加する

### ISSUE THREAD

**Issue by agilekawabata** [redmine-patch-meetup/redmine-dev-mirror#32]

**Comment by ishikawa999** [comment]
公式にチケットあり: https://www.redmine.org/issues/9029
実装が不十分でリジェクトされたパッチあり
(仕様自体の問題はなさそう)

**Comment by sanak** [comment]
以下より、こちらのIssue側も勝手ながらクローズさせて頂きます。🙇‍♂️

https://github.com/redmine-patch-meetup/redmine-dev-mirror/pull/31#issuecomment-1441873528
> > こちらですが、今日パーミッション名を変更した類似のパッチがマージされたようでした。
> > 
> > * [Feature #38048: Introduce permission to set a project public - Redmine](https://www.redmine.org/issues/38048)
> > 
> > こちらとマージされたパッチの差分を見た感じ、パーミッション名の付け方の違いが影響したようにも思いましたが、こちらのPRと #32 の方はクローズできそうな気がしましたので、念のため記載しておきます。
> 
> こちら、類似のパッチが本家側でマージされ、コンフリクト解決が実質不可能と思われましたので、勝手ながら #32 と合わせてクローズさせて頂きます。🙇‍♂️
