### ISSUE TITLE
issueをグループにアサインしたときに X-Redmine-Issue-Assigneeヘッダが空になる

### ISSUE THREAD

**Issue by matobaa** [redmine-patch-meetup/redmine-dev-mirror#36]
Settings->issue_group_assignment を設定するとチケットの担当者にグループを割り当てられるが、このとき通知されるメールにX-Redmine-Issue-Assignee: ヘッダがあるのに値が空になっている。

**Comment by matobaa** [comment]
```patch.diff
diff --git a/app/models/mailer.rb b/app/models/mailer.rb
index 7b4ca059c..d6b81d065 100644
--- a/app/models/mailer.rb
+++ b/app/models/mailer.rb
@@ -107,7 +107,7 @@ class Mailer < ActionMailer::Base
                     'Issue-Tracker' => issue.tracker.name,
                     'Issue-Id' => issue.id,
                     'Issue-Author' => issue.author.login
-    redmine_headers 'Issue-Assignee' => issue.assigned_to.login if issue.assigned_to
+    redmine_headers 'Issue-Assignee' => (issue.assigned_to.login.present? && issue.assigned_to.login || issue.assigned_to.lastname) if issue.assigned_to
     message_id journal
     references issue
     @author = journal.user
diff --git a/test/unit/mailer_test.rb b/test/unit/mailer_test.rb
index 7c867e098..7f1bd4e2f 100644
--- a/test/unit/mailer_test.rb
+++ b/test/unit/mailer_test.rb
@@ -219,6 +219,16 @@ class MailerTest < ActiveSupport::TestCase
     assert_equal issue.author.login, mail.header['X-Redmine-Sender'].to_s
   end
 
+  def test_email_headers_should_include_assignee
+    with_settings :issue_group_assignment => 1 do
+      issue = Issue.find(6)
+      issue.init_journal(User.current)
+      issue.update(:assigned_to_id => 10)
+    end
+    mail = last_email
+    assert_equal 'A Team', mail.header['X-Redmine-Issue-Assignee'].to_s
+  end
+
   def test_plain_text_mail
     Setting.plain_text_mail = 1
     journal = Journal.find(2)
```

**Comment by matobaa** [comment]
再現手順:
フィクスチャをロードしたRedmineで、
管理→設定→チケットトラッキング→グループへのチケット割り当てを許可 にチェックし、
チケット6を A-Team にアサインする。

期待値
送信されたメールのヘッダに、ユーザをアサインしたときと同様、`X-Redmine-Issue-Assignee: A Team` となってほしい。
実際の値
`X-Redmine-Issue-Assignee: (空)` となっている

**Comment by juno-nishizaki** [comment]
少なくとも issue_edit だけでなく issue_add にも同じ対応が必要だと思います。

https://github.com/redmine-patch-meetup/redmine-dev-mirror/blob/develop/app/models/mailer.rb#L78

あと気になるのは、「issue.assigned_to.login に値が存在しなければグループだから issue.assigned_to.lastname の値を取る」というのは、「たまたまそういう動作になっているからうまく動いている」という実装依存なやり方であまりよろしくない気がします。
とはいいつつも、グループ名を取得する適切な方法がわかってないので指摘しっぱなしになってしまい申し訳ないです。

**Comment by juno-nishizaki** [comment]
連投すみません。

現行仕様は「チケットの担当者にユーザーが割り当てられているときは  `X-Redmine-Issue-Assignee` ヘッダに『ログイン ID』 をセットする」なのですね。

これを「チケットの担当者にユーザーが割り当てられているときは `X-Redmine-Issue-Assignee` に『ログイン ID』 をセットして、グループが割り当てられているときは『グループ 名』をセットする」に変えようとしているのですね。

ユーザーとグループで性質の違う情報なので、このような仕様でいいのか判断が難しいですね。（グループが空なのは良くないと思いますが…）

ちなみに、グループ名は おそらく lastname を直接呼び出すより name を呼んだ方が良さそうな気がします。
`app/models/group.rb` に以下のようなメソッドが定義されていました。わざわざ定義されているということは「グループ名を取得するときは name を使いましょう」というのを明示しているものだと推測できます。

https://github.com/redmine/redmine/blob/master/app/models/group.rb#L53-L55

もし直すとしたら以下のような感じでしょうか… （クラスの比較の仕方がこれでいいのかとか、3 項演算子を使ってもいいのかというのはいったん置いといて）

```ruby
    redmine_headers 'Issue-Assignee' =>
      (issue.assigned_to.is_a?(User) ?  issue.assigned_to.login : issue.assigned_to.name) if issue.assigned_to
```

※ 担当者がユーザーの場合も同じく issue.assigned_to.name をセットするように仕様変更できれば楽なのですが、メールヘッダとはいえ外部インターフェース仕様になっているだろうから、これを変えるのは困難そうですね…

**Comment by sanak** [comment]
私も、@juno-nishizaki さんの2つ目の方法が良さそうに思いました。  
実際の動作確認や、パッチ作成などは、別途必要になると思いますが、取り急ぎ...。

**Comment by vividtone** [comment]
> ユーザーとグループで性質の違う情報なので、このような仕様でいいのか判断が難しいですね。（グループが空なのは良くないと思いますが…）

以下のような形式はどうでしょうか。

```
X-Redmine-Issue-Assignee: Group (A Team)
```

* ログインIDの代わりに "Group" という文字列をセット
* ログインIDには大文字は使えないので "Group" というログインIDが存在することはない（実際のユーザーとかぶらない）
* グループ名は括弧書きで表示

グループ名を括弧で囲むやり方は、メールのヘッダのFromなどで使われることがあるコメントの記法を参考にしました（例: `john@example.com (John Smith)`）。

括弧は本来はコメントであり、メールのヘッダフィールド内でアドレスと表示名を書く場合は `John Smith <john@example.com>` が本来の形式ですが、かつては一部のメーラーは `john@example.com (John Smith)` を使う実装を行っていました。

今回の私の提案では、`X-Redmine-Issue-Assignee: #{login}` という形式との互換性・一貫性を考慮して、ログインIDの位置に代替文字列 `Group` を置いて、その後に括弧書きでグループ名（表示名）を括弧書きで置く形式としています。

**Comment by matobaa** [comment]
ご意見ありがとうございます。賛成です。
パッチ作り直してみました:
```diff
diff --git a/app/models/mailer.rb b/app/models/mailer.rb
index 7b4ca059c..0d8a4718e 100644
--- a/app/models/mailer.rb
+++ b/app/models/mailer.rb
@@ -107,7 +107,8 @@ class Mailer < ActionMailer::Base
                     'Issue-Tracker' => issue.tracker.name,
                     'Issue-Id' => issue.id,
                     'Issue-Author' => issue.author.login
-    redmine_headers 'Issue-Assignee' => issue.assigned_to.login if issue.assigned_to
+    redmine_headers 'Issue-Assignee' => issue.assigned_to.login if issue.assigned_to.is_a?(User)
+    redmine_headers 'Issue-Assignee' => "Group (#{issue.assigned_to.name})" if issue.assigned_to.is_a?(Group)
     message_id journal
     references issue
     @author = journal.user
diff --git a/test/unit/mailer_test.rb b/test/unit/mailer_test.rb
index 7c867e098..13ddb6127 100644
--- a/test/unit/mailer_test.rb
+++ b/test/unit/mailer_test.rb
@@ -219,6 +219,33 @@ class MailerTest < ActiveSupport::TestCase
     assert_equal issue.author.login, mail.header['X-Redmine-Sender'].to_s
   end
 
+  def test_email_headers_shouldnt_include_assignee_when_not_assigned
+    issue = Issue.find(6)
+    issue.init_journal(User.current)
+    issue.update(:status_id => 4)
+    issue.update(:assigned_to_id => nil)
+    mail = last_email
+    assert !mail.header['X-Redmine-Issue-Assignee']
+  end
+  
+  def test_email_headers_should_include_assignee_when_assigned
+    issue = Issue.find(6)
+    issue.init_journal(User.current)
+    issue.update(:assigned_to_id => 2)
+    mail = last_email
+    assert_equal issue.assigned_to.login, mail.header['X-Redmine-Issue-Assignee'].to_s
+  end
+
+  def test_email_headers_should_include_assignee_if_assigned_to_group
+    issue = Issue.find(6)
+    with_settings :issue_group_assignment => 1 do
+      issue.init_journal(User.current)
+      issue.update(:assigned_to_id => 10)  # Group: A Team
+    end
+    mail = last_email
+    assert_equal "Group (#{issue.assigned_to.name})", mail.header['X-Redmine-Issue-Assignee'].to_s
+  end
+
   def test_plain_text_mail
     Setting.plain_text_mail = 1
     journal = Journal.find(2)
```

`assert !mail.header['X-Redmine-Issue-Assignee'] ` あたりがイマイチかも、と思っているのですが、
`assert_not_include` やら `mail.header.include?` やらを試したものの、「ヘッダに含まれないこと」をどう書いていいのかわからず……

**Comment by ishikawa999** [comment]
@matobaa 

> assert !mail.header['X-Redmine-Issue-Assignee'] あたりがイマイチかも、と思っているのですが、
> assert_not_include やら mail.header.include? やらを試したものの、「ヘッダに含まれないこと」をどう書いていいのかわからず……
> 
> (issue_add の対応を忘れていたので追記しました)

ヘッダに含まれないこと == mail.header['X-Redmine-Issue-Assignee']に何も入っていない、という考え方で良ければassert_nilも使えると思います。（一応手元で動かしたテストではうまく通りました）
```
assert_nil mail.header['X-Redmine-Issue-Assignee']
```

**Comment by matobaa** [comment]
試してみました。ご指摘のとおり、assert  !式 に抵触する場合のエラーメッセージは Expected false to be truthy. でした。
assert_nil で確認できることがわかりました。

存在しているはずの X-Redmine-Sender も assert_nil が合格してしまうので悩んでいたのですが、
別の存在しているはずの X-Redmine-Issue-Id で試したら期待通り assert_nil が fail することがわかったので、
assert_nil を使うことにします。

**Comment by ishikawa999** [comment]
コミット済み
https://www.redmine.org/issues/35017
