### ISSUE TITLE
パッチ会前のPRのリベース時に manual rebase needed ラベルが付いてしまう

### ISSUE THREAD

**Issue by sanak** [redmine-patch-meetup/redmine-dev-mirror#72]
以下のGitHub Actionsの履歴を見る限り、
https://github.com/redmine-patch-meetup/github-actions/actions/workflows/sync-with-origin.yml

- 2021-10-23: https://github.com/redmine-patch-meetup/github-actions/runs/3982189159?check_suite_focus=true
  - 全てOK
- 2021-11-20: https://github.com/redmine-patch-meetup/github-actions/runs/4271448942?check_suite_focus=true
  - 以下のPRで `lib/redmine.rb: needs merge` のコンフリクトが発生
    - `チケットの前,次をページネーションのようにボタンにしたい`
    - `wikiリダイレクトのリセット機能 #11`
    - `Allow configuration of API limit instead of hardcoding at 100`
    - `Update done_ratio to 100% when issue is closed`
    - `Sort time entries by name, not ID`
- 2021-12-11: https://github.com/redmine-patch-meetup/github-actions/runs/4490898000?check_suite_focus=true
  - 以下のPRで `test/unit/lib/redmine/plugin_loader_test.rb: needs merge` のコンフリクトが発生
    - `#47 対象バージョンのステータスでフィルタリングが機能していないバグ修正`
    - `[WIP] Task/30-2 デフォルトで新しいプロジェクトは公開にするをデフォルトオフにする`
    - `Supporting multiple tracker_id in issues Rest API`
    - `チケット一覧の列幅を変更できるようにする`
    - `Task/48`
    - `[WIP] Task/30 デフォルトで新しいプロジェクトは公開にするをデフォルトオフにする`
    - `Feature #4437: Add timestamp in custom fileds`
    - `Task/34 活動タブ：チケットの一番古い履歴が最新のチケットステータスと同じになる問題`
- 2021-01-15: https://github.com/redmine-patch-meetup/github-actions/runs/4824001447?check_suite_focus=true
  - `23980/svg-icons` を除いて、 `manual rebase needed` ラベルが付いていたために全てリベース処理がスキップ

のような形となっていました。

いずれも、最新developブランチとのコンフリクトが生じているのが原因と考えられたため、一旦、各PRブランチについて、最新developブランチからリベースし、 `manual rebase needed` ラベルを除去するようにします。

**Comment by matobaa** [comment]
これって `manual rebase needed` がついているブランチだけ対応すればいいんですよね? (すでにいくつか対応しちゃいました)
それとも、PRがないブランチで、いまの `develop` = 02f1476d9 を親に持たないブランチも拾っていきますか?

**Comment by sanak** [comment]
@matobaa すいません、コメント見落としてました。

> これって manual rebase needed がついているブランチだけ対応すればいいんですよね? (すでにいくつか対応しちゃいました)

はい。すでにいくつか対応の旨、了解です。ありがとうございます！

今ほど、残りのPRで `manual rebase needed` ラベルが付いていたものもリベース対応しました。

---

> それとも、PRがないブランチで、いまの develop = 02f1476 を親に持たないブランチも拾っていきますか?

こちらは、これからPRを作成する際にリベースしてからフォースプッシュ頂ければと思いますので、今回は対応不要かもしれません。(次回パッチ会開催時に改めて作業する形で良いと思います。)

**Comment by sanak** [comment]
こちら、多分次回リベース時に問題なく動作すると思いますので、一旦完了扱いとします。 🙇‍♂️

**Comment by sanak** [comment]
前回リベース時に全体では問題なかったようなので、一旦クローズします。
(新たに `manual rebase needed` ラベルが付いた3件(#1, #3, #21)については、私の方で再度手動対応しておきます。)

**Comment by sanak** [comment]
どうも前回(3/19)の更新時に、再び `manual rebase needed` ラベルが付いてしまったようなので、リオープンします...。
明日の午前中に対応できそうなところは対応するかもしれません。

**Comment by matobaa** [comment]
やっつけときました

**Comment by sanak** [comment]
@matobaa 対応ありがとうございます！ 🙇
