### ISSUE TITLE
Change branch name from `development` to `develop`

### ISSUE THREAD

**Issue by urimaro** [redmine-patch-meetup/redmine-dev-mirror#9]
I think `develop` is more common.
It might be easier to treat because the word length is short.

**Comment by urimaro** [comment]
I pushed the 'develop' branch made from the 'development' branch.
Would you consider making the 'develop' branch default?

**Comment by kfischer-okarin** [comment]
I changed the default branch of all Pull Requests and the scripts

**Comment by urimaro** [comment]
@kfischer-okarin 
Thanks!
